//
//  EmitterLayerConfiguration.swift
//  ConfettiAnimation
//
//  Created by Samuel Lupton on 10/1/25.
//

import QuartzCore
import UIKit

protocol EmitterLayerConfiguration {
    /// The position of the emitter layer in its parent coordinate space.
    var emitterPosition: EmitterPosition { get set }
    
    /// The geometric shape used by the emitter layer to emit particles.
    var emitterShape: CAEmitterLayerEmitterShape { get set }
    
    /// The emission mode determining how particles are created and rendered.
    var emitterMode: CAEmitterLayerEmitterMode { get set }
    
    /// The size of the emitter layer, affecting the area over which particles are emitted.
    var emitterSize: CGSize { get set }
    
    /// The rate at which new particles are generated by the emitter layer.
    var birthRate: Float { get set }
    
    /// The lifetime of particles emitted by the layer, in seconds.
    var lifetime: Float { get set }
    
    /// Indicates whether the emitter layer should automatically redraw when its bounds change.
    var needsDisplayOnBoundsChange: Bool { get set }
    
    /// Configuration object defining properties for individual particles (cells).
    var cellConfiguration: ParticleCell { get set }
    
    /// Array of images used as the visual content for the particles.
    var content: [UIImage] { get }
    
    /// Generates a basic animation to be applied to the emitter layer.
    /// - Returns: A `CABasicAnimation` configured for the emitter's properties.
    func getAnimation() -> CABasicAnimation
}
